env:
  global:
    - GCP_PROJECT_ID=devops-examen-2020
    - tf_version=0.12.19
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - APP_URL=4445fdfb-f955-4df8-91f7-099d22cf4bdd
    - TENANT=07081c28-29b5-4f71-b511-61824e32846a
    - secure: azZyFUxe+T5s8X41YGDyY/9SUqdVSTRS+yHgQ1+zIb0xBX+O4RvQLanv/ndn0JcHDnFUSHQ7G1xYCzEQbyAjLQjljkM7crtTVcHKGSPZzmbpU9nKfo/ggHV32pJNUtzj19k60C1EWsowY6OsS42qASoI6EB3zVYk2p3Vt9u4NAxHfFljr7l2XEJiuCTnT6ibu7d7Eiha4ymcKyggvPwOuUnfXwgSP6V0l0UKOgN/oJvaL+QkU3rQhyzqqlFV29U/vqa26Vx6RBQ/X5kg8pa641hMJF1Fh/B+X7r0Iwc9DCJ/+1CoPNDbhPolWdCCDUUzZ/HpSXOAeUifudPP4ylCQaAJSdKpEc17Ch10BXBIX+3IBdDUg1Glj+4NIFlBF51uQKIwzWdNAFKX9LravEEyAcqE/kocDTIbNZw+7MzO5v2pqS4LL8QgnxOaPlFWlYpzfafoSTefZ6gXrYYYYFnl+TuLNau/QZ8igCvTaJ3BgDsAiWJupj1YkdGz8tNSLo+nZLH9xUwC6rN7/qwgOHWb1t/z02V7Wb23ATMZDeTnW4J42jbLY6OLxW17FefvxsG4DClnKi/3CbtdhIned5ytRYc48TsdkwksidIWI4vwVXbmwgYLHD6DjNsGAsznw/WJPuDc6xMrtd8msRs2sicSNrJLFC7xcUbXkzoWk34JsIA=
    - secure: GtS191EV6lpHWlKIVA8y6qRAo/QNG1KS4IbjnlUeeVOeqoIdGGIcajLjoXw9pp87mnMrAWZftfNCncwlcL3gbcXFSpJnR43tHS7cdC/ueA/5sZhpATU8pwqd6kQMAPhgEbJD+ft9SK5nXW50RWwFMwa0etAjW9ypAtvFVr3UZgwQgeI1XPpNPIGbbYcgNfzkqm8E7iornZ8LQWGRAaLM2L4CIO8GE1H0BS6/QS0dv76YQ9vMkIswmH1x1cikFZgTxU9XSg7W44nSxuQGx1uNeknMjSdv2u2s/x14k23g6dfE4+NPiu1/NB49bxefBFSGd7II4AZAvW5B2/TaedNoZuc8NPiUHa8B1obiJ8gUS8Xd3fS3Bo8+hLdKhcouIptBCNuRqecFq+xbJGPMpI95NmWIa+NsAjkX7C2Eh7CIlyHd+Tw6L4cLEdHX4gM2mTFbZX5zsQH97JLHjCJRreZprM1tqZIuHh0LliCqpbyFjXjr+N44trb1qbQRy1R9fRYP9VhlOiYicuAW2ZKstpMDg9EjPCg8KAN8l7jsjk2g9vaIL3tmgVy0T++r4AXpoRCY+75LuO1F404gDH9tifOThePQx6CmeD0QENCfvAydNjBLoOkhPsmiv9bzlphynY75uyuLW8vAeBojXCj7juxTZxauMPDP7/KrPVCtW8SKX6E=
branches:
  only:
    - main
before_install:
  - openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv
    -in google-key.json.enc -out google-key.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  - gcloud auth activate-service-account --key-file=google-key.json
  - gcloud config set project "${GCP_PROJECT_ID}"
  - export GOOGLE_APPLICATION_CREDENTIALS=./google-key.json
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip
  - az login --service-principal -u $APP_URL  -p $AZURE_PASSWORD --tenant $TENANT
install: true
script:
  - |-
    set -ex;

  export TF_VAR_statuscake_key=$(gcloud secrets versions access latest --secret=STATUSCAKE_KEY)
  export TF_VAR_opsgenie_key=$(gcloud secrets versions access latest --secret=OPSGENIE_KEY)
  export TF_VAR_logz_token=$LOGZ_TOKEN
  terraform init
  terraform plan
  terraform apply --auto-approve
  terraform output
