env:
  global:
  - GCP_PROJECT_ID=devops-examen-2020
  - tf_version=0.12.19
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: azZyFUxe+T5s8X41YGDyY/9SUqdVSTRS+yHgQ1+zIb0xBX+O4RvQLanv/ndn0JcHDnFUSHQ7G1xYCzEQbyAjLQjljkM7crtTVcHKGSPZzmbpU9nKfo/ggHV32pJNUtzj19k60C1EWsowY6OsS42qASoI6EB3zVYk2p3Vt9u4NAxHfFljr7l2XEJiuCTnT6ibu7d7Eiha4ymcKyggvPwOuUnfXwgSP6V0l0UKOgN/oJvaL+QkU3rQhyzqqlFV29U/vqa26Vx6RBQ/X5kg8pa641hMJF1Fh/B+X7r0Iwc9DCJ/+1CoPNDbhPolWdCCDUUzZ/HpSXOAeUifudPP4ylCQaAJSdKpEc17Ch10BXBIX+3IBdDUg1Glj+4NIFlBF51uQKIwzWdNAFKX9LravEEyAcqE/kocDTIbNZw+7MzO5v2pqS4LL8QgnxOaPlFWlYpzfafoSTefZ6gXrYYYYFnl+TuLNau/QZ8igCvTaJ3BgDsAiWJupj1YkdGz8tNSLo+nZLH9xUwC6rN7/qwgOHWb1t/z02V7Wb23ATMZDeTnW4J42jbLY6OLxW17FefvxsG4DClnKi/3CbtdhIned5ytRYc48TsdkwksidIWI4vwVXbmwgYLHD6DjNsGAsznw/WJPuDc6xMrtd8msRs2sicSNrJLFC7xcUbXkzoWk34JsIA=
  - secure: p5Ug+jvDbEPBzI62yCcKUtIMoIvJViMLsQt0/cmjGVHcmpugZybAGBpvnORMQeYl06gre4XuMp+xKxkZdWEQ2Lfw59DhSKNPHHWdv6y50CwvjoioB3qRNkw0VAPjzCguP7uUeahpklgrvn8JpMZMOBzJByWF7GTBnBrqIR+S8MxrCstyAwSXnfWhsvAVp2+oPzpIObEraG2ApagmWUTONFfMYX6qUTjrJsoy7TCe1qBklu9oq/z601mYVjh+EThpeKo2+DLLBSUqIpWAARaMbS4A2zl+zB26L+/sAQBxC3LIhUmXQErOgjb1z4LEwUwUQnYOggKjsmwY1/ZsjY4hvR/oY8R/V9/XhNVqXZo1qsMRqwWPFLkbcXVsdCjq0uLqIurk97BH1W+KSFnQIDtXtwJDg/Yo4rtnyf6ZkszHO7ZLHnsHI3o35roRqz8QSRB16r75PpiX0M0bUUkZz5AQvOy5jG4Yc6GKutBCKaelVJ2gxmJI+IZerqD511chZVDVh+WBry6Otd9CRkWM564kjk7tkHJmUQ5R7RRAqPHccgzeRrqg2cUtx+a/Xzx66f6qxBniejU6tWKCyMHXXSIXndEOH0mST4Z1kiWWLORIkUcXxRmUPsi3ALcqhw67bodKcBDxEQGchOViB0TWbWtR2BumNd0dP3npiGlN8cS6cmY=
  - secure: vVSxcI1tFxacxZns6Z3+n4bnB/yNZvRGuHIh+d4xbOlPZXf73IyCLFTMIwaq7MCl5BLt2z+/Eu+wfKzrOkiuLGsVKrDrEpdMNC8SNRGV/KmgbjUGM4tmo6NBLp77bhXg4ytWStnRCd+BYgTQvYooqxWJVM3tsntUYmoxiUbdzkUlPWhR4NFUvT7H3MVSomCWtN8Xg6h1D2awJ4IecJAdU07f7DDG5uR7ee0z+g8B8pxHQZso3nXKzXeCK4+m+DmpZbyIYGagcqMNyeLfuIo/pc994bGMQynUVB06i4FtAbutmSGMZ0k8nSxvoZ3t+ilM72YsT+Gu2jhzykDZ8IZ/MtVz5ivX3mXU4+JIsNn4G/Rh5137hoW+sz30fk5YzBAU5ajBiYiC+8fO39SxSoo5vciJBiXugdw4h0WOUwPdKGbGD/5gLf+QYBDTtK4Do/ZpAojNbKvZFgfw1EX8Wi19ZB8PLNCzG6M8kmCK/NmF3dRw4oILFfPWbsAJ9leCVxKjrbv5P6VZbWSGDCt1HSZ94+hz4uW1YEfxGpSUpXvwZ9rMwIzJilKfHcypWbbYkuuYF20D77zT9lFVWoGtt/B4V387sz4G5EqJOpUJdtEO8HDLnekNYFKguQXxAxFCRZhTiCvMGJ6wXWUYH/gNwf6IkEC4TNAi51GhbFZxILj7xmU=
branches:
  only:
  - main
before_install:
- openssl aes-256-cbc -K $encrypted_98d237b7dbf4_key -iv $encrypted_98d237b7dbf4_iv
  -in google-key.json.enc -out google-key.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=google-key.json
- gcloud config set project "${GCP_PROJECT_ID}"
- export GOOGLE_APPLICATION_CREDENTIALS=./google-key.json
- wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
- unzip terraform_"$tf_version"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
- set -ex;
- export TF_VAR_statuscake_key=$STATUSCAKE_KEY
- export TF_VAR_logz_token=$LOGZ_TOKEN
- export TF_VAR_pagerduty_token=$PAGERDUTY_TOKEN
- terraform init
- terraform plan
- terraform apply --auto-approve
- terraform output
